#!/bin/bash

PROJECT_ID=$shell gcloud info --format='value(config.project)'

# GCP REGION
REGION=asia-southeast1

# SHARED
SHARED_CLUSTER_NAME=shared
SHARED_PROJECT_ID=$USER-$SHARED_CLUSTER_NAME
SHARED_GKE_SA=$SHARED_CLUSTER_NAME-gke-service-account
SHARED_GKE_SA_EMAIL=$SHARED_GKE_SA@$SHARED_PROJECT_ID.iam.gserviceaccount.com
SHARED_ZONE=asia-southeast1-a
SHARED_ZONE2=asia-southeast1-b

# DEV
DEV_CLUSTER_NAME=dev
DEV_PROJECT_ID=$USER-$DEV_CLUSTER_NAME
DEV_GKE_SA=$DEV_CLUSTER_NAME-gke-service-account
DEV_GKE_SA_EMAIL=$DEV_GKE_SA@$DEV_PROJECT_ID.iam.gserviceaccount.com
DEV_ZONE=asia-southeast1-a
DEV_ZONE2=asia-southeast1-b

# PROD
PROD_CLUSTER_NAME=prod
PROD_PROJECT_ID=$USER-$PROD_CLUSTER_NAME
PROD_GKE_SA=$PROD_CLUSTER_NAME-gke-service-account
PROD_GKE_SA_EMAIL=$PROD_GKE_SA@$PROD_PROJECT_ID.iam.gserviceaccount.com
PROD_ZONE=asia-southeast1-a
PROD_ZONE2=asia-southeast1-b

# HALYARD SERVICE ACCOUNT
HALYARD_SA=halyard-service-account
HALYARD_SA_EMAIL=$HALYARD_SA@$SHARED_PROJECT_ID.iam.gserviceaccount.com

# HALYARD INSTANCE
HALYARD_ZONE=$SHARED_ZONE
HALYARD_INSTANCE=$SHARED_PROJECT_ID-halyard
HALYARD_MACHINE_TYPE=n1-standard-1

# SPINNAKER SERVICE ACCOUNT 
SPINNAKER_SA=spinnaker-service-account
SPINNAKER_SA_EMAIL=$SPINNAKER_SA@$SHARED_PROJECT_ID.iam.gserviceaccount.com

# SPINNAKER CREDENTIAL DESTINATION
SPINNAKER_SA_DEST=~/.gcp/gcp.json

# SPINNAKER BUCKET
SPINNAKER_BUCKET_LOCATION=asia

# OAUTH CREDENTIALS
CLIENT_ID=CHANGE_OAUTH_CLIENT_ID
CLIENT_SECRET=CHANGE_OAUTH_CLIENT_SECRET
OAUTH_ALLOWED_DOMAIN=CHANGE_OAUTH_ALLOWED_DOMAIN

# RESERVED STATIC IPS
SPINNAKERUI=SPINNAKER_UI_IP
SPINNAKERAPI=SPINNAKER_API_IP

# Create DNS record for the following:
# spinnaker.$SPINNAKER_DOMAIN_URL = $SPINNAKERUI
# spinnaker-api.$SPINNAKER_DOMAIN_URL = $SPINNAKERAPI
SPINNAKER_DOMAIN_URL=CHANGE_SPINNAKER_DOMAIN_URL
