#/bin/bash
# Usage: . set-vars.sh

PROJECT_ID=$(gcloud info --format='value(config.project)')
# BILLING ACCOUNT
GCP_BILLING_ACCOUNT=0X0X0X-0X0X0X-0X0X0X
# GCP REGION
REGION=asia-southeast1

# RANDOM ID
if [ -f random.txt ]; then
  RANDOM_ID=$(cat random.txt)
else
  RANDOM_ID="$RANDOM"
  echo $RANDOM_ID > random.txt
fi

# SHARED
SHARED_CLUSTER_NAME=shared
SHARED_PROJECT_ID=$SHARED_CLUSTER_NAME-$RANDOM_ID
SHARED_GKE_SA=$SHARED_CLUSTER_NAME-gke-sa
SHARED_GKE_SA_EMAIL=$SHARED_GKE_SA@$SHARED_PROJECT_ID.iam.gserviceaccount.com
SHARED_NUM_NODES=1
SHARED_MIN_NODES=1
SHARED_MAX_NODES=4
SHARED_ZONE=asia-southeast1-a
SHARED_ZONE2=asia-southeast1-b
SHARED_CLUSTER_VERSION=1.8.8-gke.0
SHARED_MACHINE_TYPE=n1-standard-2
SHARED_DISK_SIZE=100
# DEV
DEV_CLUSTER_NAME=dev
DEV_PROJECT_ID=$DEV_CLUSTER_NAME-$RANDOM_ID
DEV_GKE_SA=$DEV_CLUSTER_NAME-gke-sa
DEV_GKE_SA_EMAIL=$DEV_GKE_SA@$DEV_PROJECT_ID.iam.gserviceaccount.com
DEV_NUM_NODES=1
DEV_MIN_NODES=1
DEV_MAX_NODES=4
DEV_ZONE=asia-southeast1-a
DEV_ZONE2=asia-southeast1-b
DEV_CLUSTER_VERSION=1.9.6-gke.1
DEV_MACHINE_TYPE=n1-standard-2
DEV_DISK_SIZE=100
# PROD
PROD_CLUSTER_NAME=prod
PROD_PROJECT_ID=$PROD_CLUSTER_NAME-$RANDOM_ID
PROD_GKE_SA=$PROD_CLUSTER_NAME-gke-sa
PROD_GKE_SA_EMAIL=$PROD_GKE_SA@$PROD_PROJECT_ID.iam.gserviceaccount.com
PROD_NUM_NODES=1
PROD_MIN_NODES=1
PROD_MAX_NODES=4
PROD_ZONE=asia-southeast1-a
PROD_ZONE2=asia-southeast1-b
PROD_CLUSTER_VERSION=1.8.8-gke.0
PROD_MACHINE_TYPE=n1-standard-2
PROD_DISK_SIZE=100
